---
title: "Bayesian analysis (Grade 6-10) - Results"
author: "Michael Wu"
date: "2023-06-20"
output:
  pdf_document: default
  html_document: default
  word_document: default
---

# Load fitted models

```{r}
library(report)
library(tidyverse)
library(insight)
library(bayestestR)

load("/Users/michaelfive/Library/CloudStorage/GoogleDrive-wuzezhen33@gmail.com/My Drive/Nepal SA Study/Analysis/model/gr6-10_survey_gpa_0820.RData")
```

# Results reporting
## Tables

### School Descriptives

```{r}
sch_t1 <- dat_s %>%
  group_by(sch_id, grade) %>%
  summarize(count = n(), .groups = 'drop') %>%
  group_by(sch_id) %>%
  mutate(percentage = paste0(round((count / sum(count)) * 100, 2), "%")) |> 
  select(-count)

sch_t2 <- dat_s %>%
  group_by(sch_id, gender) %>%
  summarize(count = n(), .groups = 'drop') %>%
  group_by(sch_id) %>%
  mutate(percentage = paste0(round((count / sum(count)) * 100, 2), "%")) |> 
  select(-count) |> 
  na.omit()

sch_t3 <- dat_s %>%
  group_by(sch_id) |> 
  summarise(age_m = round(mean(age_b, na.rm = T), 2),
            age_sd = round(sd(age_b, na.rm = T), 2))
```


### Main Impact Models
```{r, results='asis'}
par <- c("Intercept", "Baseline GPA", "Treatment (Affirmed vs. Control)", 
           "Class Size", 
           "Grade 7 (vs. Grade 6)", "Grade 8 (vs. Grade 6)", "Grade 9 (vs. Grade 6)",
           "Grade 10 (vs. Grade 6)",
           "Gender (Male vs. Female)", "Age",
           "Disability Status (Hearing vs. Deaf)",
           "Father Education (Basic education (Class 1 to 8) vs. Bachelor and above)",
           "Father Education (Do not go to school vs. Bachelor and above)",
           "Father Education (Non-response vs. Bachelor and above)",
           "Father Education (Secondary education (Class 9 to 12) vs. Bachelor and above)",
           "Father Education (Some college education vs. Bachelor and above)",
           
           #"Mother Education (Basic education (Class 1 to 8) vs. Bachelor and above)",
           "Mother Education (Do not go to school vs. Bachelor and above)",
           "Mother Education (Non-response vs. Bachelor and above)",
           "Mother Education (Secondary education (Class 9 to 12) vs. Bachelor and above)",
           "Mother Education (Some college education vs. Bachelor and above)",         
           
           "Father Occupation (Non-salary job vs. No job)",
           "Father Occupation (Salary job vs. No job)",
           "Mother Occupation (Non-salary job vs. No job)",
           "Mother Occupation (Salary job vs. No job)", 
           
           "Number of Adult Members in Household",
           "Number of Siblings",
           
           "Duration of the Values Affirmation Session (in minutes)",
           "Kathmandu School (vs. Baglung School)",
           "Pokhara School (vs. Baglung School)",
           
           "SD_Class_Intercept",
           "SD_Class_Treatment",
           "Cor_Class_Intercept_Treatment",
           "Residual SD"
  )

tab_gpa <- create_main_tab(fit = fit_gpa, par = par)

write_csv(tab_gpa, "analysis/tables/tab_gpa.csv")
```

```{r}
par <- c("Intercept", "Baseline self-efficacy and sense of belonging in school",
         "Treatment (Affirmed vs. Control)", 
           "Class Size", 
           "Grade 7 (vs. Grade 6)", "Grade 8 (vs. Grade 6)", "Grade 9 (vs. Grade 6)",
           "Grade 10 (vs. Grade 6)",
           "Gender (Male vs. Female)", "Age",
           "Disability Status (Hearing vs. Deaf)",
           "Father Education (Basic education (Class 1 to 8) vs. Bachelor and above)",
           "Father Education (Do not go to school vs. Bachelor and above)",
           "Father Education (Non-response vs. Bachelor and above)",
           "Father Education (Secondary education (Class 9 to 12) vs. Bachelor and above)",
           "Father Education (Some college education vs. Bachelor and above)",
           
           #"Mother Education (Basic education (Class 1 to 8) vs. Bachelor and above)",
           "Mother Education (Do not go to school vs. Bachelor and above)",
           "Mother Education (Non-response vs. Bachelor and above)",
           "Mother Education (Secondary education (Class 9 to 12) vs. Bachelor and above)",
           "Mother Education (Some college education vs. Bachelor and above)",         
           
           "Father Occupation (Non-salary job vs. No job)",
           "Father Occupation (Salary job vs. No job)",
           "Mother Occupation (Non-salary job vs. No job)",
           "Mother Occupation (Salary job vs. No job)", 
           
           "Number of Adult Members in Household",
           "Number of Siblings",
           
           "Duration of the Values Affirmation Session (in minutes)",
           "Kathmandu School (vs. Baglung School)",
           "Pokhara School (vs. Baglung School)",
         
           "Baseline GPA",
           
           "SD_Class_Intercept",
           "SD_Class_Treatment",
           "Cor_Class_Intercept_Treatment",
           "Residual SD"
  )

tab_f1 <- create_secondary_tab(fit = fit_f1, par = par)

write_csv(tab_f1, "analysis/tables/tab_f1.csv")
```

```{r}
par[2] <- "Baseline stereotype threat"

tab_f2 <- create_secondary_tab(fit = fit_f2, par = par)

write_csv(tab_f2, "analysis/tables/tab_f2.csv")
```

```{r}
par[2] <- "Baseline academic stress"

tab_f3 <- create_secondary_tab(fit = fit_f3, par = par)

write_csv(tab_f3, "analysis/tables/tab_f3.csv")
```

### Moderation Effect Models
```{r, results='asis'}
par <- c("Intercept", "Baseline GPA", "Treatment (Affirmed vs. Control)", 
           "Class Size", 
           "Grade 7 (vs. Grade 6)", "Grade 8 (vs. Grade 6)", "Grade 9 (vs. Grade 6)",
           "Grade 10 (vs. Grade 6)",
           "Gender (Male vs. Female)", "Age",
           "Disability Status (Hearing vs. Deaf)",
           "Father Education (Basic education (Class 1 to 8) vs. Bachelor and above)",
           "Father Education (Do not go to school vs. Bachelor and above)",
           "Father Education (Non-response vs. Bachelor and above)",
           "Father Education (Secondary education (Class 9 to 12) vs. Bachelor and above)",
           "Father Education (Some college education vs. Bachelor and above)",
           
           #"Mother Education (Basic education (Class 1 to 8) vs. Bachelor and above)",
           "Mother Education (Do not go to school vs. Bachelor and above)",
           "Mother Education (Non-response vs. Bachelor and above)",
           "Mother Education (Secondary education (Class 9 to 12) vs. Bachelor and above)",
           "Mother Education (Some college education vs. Bachelor and above)",         
           
           "Father Occupation (Non-salary job vs. No job)",
           "Father Occupation (Salary job vs. No job)",
           "Mother Occupation (Non-salary job vs. No job)",
           "Mother Occupation (Salary job vs. No job)", 
           
           "Number of Adult Members in Household",
           "Number of Siblings",
           
           "Duration of the Values Affirmation Session (in minutes)",
           "Kathmandu School (vs. Baglung School)",
           "Pokhara School (vs. Baglung School)",
         
           "Treatment X Baseline GPA",  
         
           "SD_Class_Intercept",
           "SD_Class_Treatment",
           "Cor_Class_Intercept_Treatment",
           "Residual SD"
  )

tab_gpa_x_low_performance_cont <- create_mod_tab(fit = fit_gpa_x_low_performance_cont, par = par)

write_csv(tab_gpa_x_low_performance_cont, "analysis/tables/tab_gpa_x_low_performance_cont.csv")
```

```{r, results='asis'}
par <- c("Intercept", "Baseline GPA", "Treatment (Affirmed vs. Control)", 
         "Low Performance (Yes vs. No)",
           "Class Size", 
           "Grade 7 (vs. Grade 6)", "Grade 8 (vs. Grade 6)", "Grade 9 (vs. Grade 6)",
           "Grade 10 (vs. Grade 6)",
           "Gender (Male vs. Female)", "Age",
           "Disability Status (Hearing vs. Deaf)",
           "Father Education (Basic education (Class 1 to 8) vs. Bachelor and above)",
           "Father Education (Do not go to school vs. Bachelor and above)",
           "Father Education (Non-response vs. Bachelor and above)",
           "Father Education (Secondary education (Class 9 to 12) vs. Bachelor and above)",
           "Father Education (Some college education vs. Bachelor and above)",
           
           #"Mother Education (Basic education (Class 1 to 8) vs. Bachelor and above)",
           "Mother Education (Do not go to school vs. Bachelor and above)",
           "Mother Education (Non-response vs. Bachelor and above)",
           "Mother Education (Secondary education (Class 9 to 12) vs. Bachelor and above)",
           "Mother Education (Some college education vs. Bachelor and above)",         
           
           "Father Occupation (Non-salary job vs. No job)",
           "Father Occupation (Salary job vs. No job)",
           "Mother Occupation (Non-salary job vs. No job)",
           "Mother Occupation (Salary job vs. No job)", 
           
           "Number of Adult Members in Household",
           "Number of Siblings",
           
           "Duration of the Values Affirmation Session (in minutes)",
           "Kathmandu School (vs. Baglung School)",
           "Pokhara School (vs. Baglung School)",
         
           "Treatment X Low Performance",  
         
           "SD_Class_Intercept",
           "SD_Class_Treatment",
           "Cor_Class_Intercept_Treatment",
           "Residual SD"
  )

tab_gpa_x_low_performance <- create_mod_tab(fit = fit_gpa_x_low_performance, par = par)

write_csv(tab_gpa_x_low_performance, "analysis/tables/tab_gpa_x_low_performance.csv")
```

```{r}
par[c(4, 31)] <- c("Psychological Threat", "Treatment X Psychological Threat")

tab_gpa_x_psych_threat <- create_mod_tab(fit = fit_gpa_x_psych_threat, par = par)

write_csv(tab_gpa_x_psych_threat, "analysis/tables/fit_gpa_x_psych_threat.csv")
```

```{r}
par[c(4, 31)] <- c("Stereotype Threat", "Treatment X Stereotype Threat")

tab_gpa_x_stereotype_threat <- create_mod_tab(fit = fit_gpa_x_stereotype_threat, par = par)

write_csv(tab_gpa_x_stereotype_threat, "analysis/tables/fit_gpa_x_stereotype_threat.csv")
```